package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Jom! Brand Palette (Inspired by the official Jom! Electric Royal Blue & Cyan Vortex Icon)
val JomRoyalBlue = Color(0xFF0A38EB)
val JomDeepBlue = Color(0xFF051C8A)
val JomCyan = Color(0xFF00E5FF)
val JomSkyBlue = Color(0xFF1EA7FF)
val JomElectricIndigo = Color(0xFF3D5AFE)

// Light Scheme Tokens
val LightPrimary = Color(0xFF0A38EB)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE4FF)
val LightOnPrimaryContainer = Color(0xFF001258)
val LightSecondary = Color(0xFF006879)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFA8EDFF)
val LightOnSecondaryContainer = Color(0xFF001F26)
val LightTertiary = Color(0xFF006B58)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF7BF8D8)
val LightOnTertiaryContainer = Color(0xFF002019)
val LightBackground = Color(0xFFF7F9FF)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFEBF0FF)
val LightOnSurfaceVariant = Color(0xFF434B68)

// Dark Scheme Tokens
val DarkPrimary = Color(0xFF6692FF)
val DarkOnPrimary = Color(0xFF001E85)
val DarkPrimaryContainer = Color(0xFF0A38EB)
val DarkOnPrimaryContainer = Color(0xFFDCE4FF)
val DarkSecondary = Color(0xFF00E5FF)
val DarkOnSecondary = Color(0xFF003640)
val DarkSecondaryContainer = Color(0xFF004E5C)
val DarkOnSecondaryContainer = Color(0xFFA8EDFF)
val DarkTertiary = Color(0xFF5CDBBD)
val DarkOnTertiary = Color(0xFF00382D)
val DarkTertiaryContainer = Color(0xFF005142)
val DarkOnTertiaryContainer = Color(0xFF7BF8D8)
val DarkBackground = Color(0xFF070C1F)
val DarkOnBackground = Color(0xFFEFF3FF)
val DarkSurface = Color(0xFF0E1530)
val DarkOnSurface = Color(0xFFEFF3FF)
val DarkSurfaceVariant = Color(0xFF1A254B)
val DarkOnSurfaceVariant = Color(0xFFB5C2E8)

// Status & Semantic Accents
val OnlineEmerald = Color(0xFF10B981)
val WarningAmber = Color(0xFFF59E0B)
val DangerCrimson = Color(0xFFEF4444)
val OutgoingBubbleLight = Color(0xFF0A38EB)
val IncomingBubbleLight = Color(0xFFEFF4FF)
val OutgoingBubbleDark = Color(0xFF1545F6)
val IncomingBubbleDark = Color(0xFF1A254B)
